### ISSUE TITLE
Setup Android studio environment

### ISSUE THREAD

**Issue by chudoklates** [chudoklates/light-sensor-app#1]

**Comment by kmezynski** [comment]
Android studio was installed successfully. It's supported by every common OS and can be downloaded from the [Android's webpage](https://developer.android.com/studio?gclid=Cj0KCQjwkbuKBhDRARIsAALysV4E6Jsw8D2qsZ6BPpHayTtXk-qavS2ML2bi-nCUjeRwGx6fMEdT354aAsa7EALw_wcB&gclsrc=aw.ds#downloads). After installation it's higly recommended to [configure VM acceleration](https://developer.android.com/studio/run/emulator-acceleration?utm_source=android-studio#vm-linux).
