### ISSUE TITLE
Create initial project setup with React Native

### ISSUE THREAD

**Issue by chudoklates** [chudoklates/light-sensor-app#2]
- package config
- react-native cli setup
- SDK setup

**Comment by kmezynski** [comment]
To build React Native apps for Android, install OracleJDK 11 and Node.js Erbium (install via [nvm](https://github.com/nvm-sh/nvm)) first:
```bash
sudo apt install openjdk-11-jre
nvm install lts/erbium
nvm use lts/erbium
```
Next, proceed with [React Native CLI](https://reactnative.dev/docs/environment-setup) itself.
If all the above dependencies are fulfilled, proceed with running the application:
```bash
git clone https://github.com/chudoklates/light-sensor-app/tree/master
cd light-sensor-app
git checkout 6ab18bab13ece586a0b4ff4cc24d74af97df31d0
npm install
npx react-native start
npm run android
```
`npx react-native start` is optional in case when `npm run android` doesn't start the app. In the AVD should appear prompt: 
> Open up App.js to start working on your app!
