### ISSUE TITLE
Display sensor data on the front-end

### ISSUE THREAD

**Issue by chudoklates** [chudoklates/light-sensor-app#4]

**Comment by kmezynski** [comment]
After installing & integrating sensor library (#3), there was added hook to handle light sensor functionality. Output value is displayed directly on the screen in lux (commit: f41b368). To start app in the emulator run:
```bash
npx react-native start
npm run android
```
Follow linked tutorial to test and [run apps on device](https://reactnative.dev/docs/running-on-device).
